### ISSUE TITLE
 error: non-void function does not return a value [-Werror,-Wreturn-type]

### ISSUE THREAD

**Issue by Balasnest** [square/Valet#302]
Facing this error in Xcode **14.3.1**. But its working fine in **Xcode 14.2**

```
ios/Pods/Valet/Valet/VALSecureEnclaveValet.m:274:1: error: non-void function does not return a value [-Werror,-Wreturn-type]
}
^
/Users/bm/zeta/zc/payzapp/ios/Pods/Valet/Valet/VALSecureEnclaveValet.m:279:1: error: non-void function does not return a value [-Werror,-Wreturn-type]
}
^
2 errors generated.
```
![Screenshot 2023-08-01 at 7 44 25 PM](https://github.com/square/Valet/assets/6050520/e8a34b73-340a-43bb-ace3-8b52b59d9556)

**Comment by jshier** [comment]
This was resolved in 4.2.0, make sure you update.

**Comment by dfed** [comment]
Closing as fixed since this doesn't repro in the latest release. Please let us know if you find compilation problems in the latest release.
